server:
  port: 8008

spring:
  application:
    name: gateway

cloud:
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: nacos-provider
